services:
  fcld:
    build: .
    image: fcld:latest
    network_mode: host
    volumes:
      - ./shows:/app/shows:ro
    environment:
      - OLA_HOST=127.0.0.1
      - OLA_PORT=9010
    command: demo
